import path from "node:path"

const root = path.resolve(import.meta.dirname, "../..")
const source = path.join(root, "script/opencode/codex-web-search.ts")
const target = path.join(root, ".opencode/plugin/codex-web-search.ts")
const header = "// Generated by bun run build:opencode-plugin. Do not edit.\n"

async function main() {
  const build = await Bun.build({
    entrypoints: [source],
    target: "bun",
    format: "esm",
    packages: "bundle",
    minify: true,
    sourcemap: "none",
    write: false,
  })
  if (!build.success) throw new AggregateError(build.logs, "Failed to build the Codex web search plugin")

  const content = `${header}${(await build.outputs[0].text()).trimEnd()}\n`
  if (process.argv.includes("--check")) {
    const current = (await Bun.file(target).exists()) ? await Bun.file(target).text() : ""
    if (current === content) return
    console.error(`${path.relative(root, target)} is stale; run bun run build:opencode-plugin`)
    process.exitCode = 1
    return
  }

  await Bun.write(target, content)
}

await main()
