/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as ConnectionIdProjectIdIndexRouteImport } from './routes/$connectionId.$projectId.index'
import { Route as SettingsConnectionIdSectionRouteImport } from './routes/settings.$connectionId.$section'
import { Route as ConnectionIdProjectIdNewDraftIdRouteImport } from './routes/$connectionId.$projectId.new.$draftId'
import { Route as ConnectionIdProjectIdSessionSessionIdIndexRouteImport } from './routes/$connectionId.$projectId.session.$sessionId.index'
import { Route as ConnectionIdProjectIdSessionSessionIdFilesRouteImport } from './routes/$connectionId.$projectId.session.$sessionId.files'
import { Route as ConnectionIdProjectIdSessionSessionIdReviewRouteImport } from './routes/$connectionId.$projectId.session.$sessionId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const ConnectionIdProjectIdIndexRoute =
  ConnectionIdProjectIdIndexRouteImport.update({
    id: '/$connectionId/$projectId/',
    path: '/$connectionId/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsConnectionIdSectionRoute =
  SettingsConnectionIdSectionRouteImport.update({
    id: '/$connectionId/$section',
    path: '/$connectionId/$section',
    getParentRoute: () => SettingsRoute,
  } as any)
const ConnectionIdProjectIdNewDraftIdRoute =
  ConnectionIdProjectIdNewDraftIdRouteImport.update({
    id: '/$connectionId/$projectId/new/$draftId',
    path: '/$connectionId/$projectId/new/$draftId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectionIdProjectIdSessionSessionIdIndexRoute =
  ConnectionIdProjectIdSessionSessionIdIndexRouteImport.update({
    id: '/$connectionId/$projectId/session/$sessionId/',
    path: '/$connectionId/$projectId/session/$sessionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectionIdProjectIdSessionSessionIdFilesRoute =
  ConnectionIdProjectIdSessionSessionIdFilesRouteImport.update({
    id: '/$connectionId/$projectId/session/$sessionId/files',
    path: '/$connectionId/$projectId/session/$sessionId/files',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectionIdProjectIdSessionSessionIdReviewRoute =
  ConnectionIdProjectIdSessionSessionIdReviewRouteImport.update({
    id: '/$connectionId/$projectId/session/$sessionId/review',
    path: '/$connectionId/$projectId/session/$sessionId/review',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/$connectionId/$section': typeof SettingsConnectionIdSectionRoute
  '/$connectionId/$projectId/': typeof ConnectionIdProjectIdIndexRoute
  '/$connectionId/$projectId/new/$draftId': typeof ConnectionIdProjectIdNewDraftIdRoute
  '/$connectionId/$projectId/session/$sessionId/files': typeof ConnectionIdProjectIdSessionSessionIdFilesRoute
  '/$connectionId/$projectId/session/$sessionId/review': typeof ConnectionIdProjectIdSessionSessionIdReviewRoute
  '/$connectionId/$projectId/session/$sessionId/': typeof ConnectionIdProjectIdSessionSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/$connectionId/$section': typeof SettingsConnectionIdSectionRoute
  '/$connectionId/$projectId': typeof ConnectionIdProjectIdIndexRoute
  '/$connectionId/$projectId/new/$draftId': typeof ConnectionIdProjectIdNewDraftIdRoute
  '/$connectionId/$projectId/session/$sessionId/files': typeof ConnectionIdProjectIdSessionSessionIdFilesRoute
  '/$connectionId/$projectId/session/$sessionId/review': typeof ConnectionIdProjectIdSessionSessionIdReviewRoute
  '/$connectionId/$projectId/session/$sessionId': typeof ConnectionIdProjectIdSessionSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/$connectionId/$section': typeof SettingsConnectionIdSectionRoute
  '/$connectionId/$projectId/': typeof ConnectionIdProjectIdIndexRoute
  '/$connectionId/$projectId/new/$draftId': typeof ConnectionIdProjectIdNewDraftIdRoute
  '/$connectionId/$projectId/session/$sessionId/files': typeof ConnectionIdProjectIdSessionSessionIdFilesRoute
  '/$connectionId/$projectId/session/$sessionId/review': typeof ConnectionIdProjectIdSessionSessionIdReviewRoute
  '/$connectionId/$projectId/session/$sessionId/': typeof ConnectionIdProjectIdSessionSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/$section'
    | '/settings/$connectionId/$section'
    | '/$connectionId/$projectId/'
    | '/$connectionId/$projectId/new/$draftId'
    | '/$connectionId/$projectId/session/$sessionId/files'
    | '/$connectionId/$projectId/session/$sessionId/review'
    | '/$connectionId/$projectId/session/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/settings/$section'
    | '/settings/$connectionId/$section'
    | '/$connectionId/$projectId'
    | '/$connectionId/$projectId/new/$draftId'
    | '/$connectionId/$projectId/session/$sessionId/files'
    | '/$connectionId/$projectId/session/$sessionId/review'
    | '/$connectionId/$projectId/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/$section'
    | '/settings/$connectionId/$section'
    | '/$connectionId/$projectId/'
    | '/$connectionId/$projectId/new/$draftId'
    | '/$connectionId/$projectId/session/$sessionId/files'
    | '/$connectionId/$projectId/session/$sessionId/review'
    | '/$connectionId/$projectId/session/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ConnectionIdProjectIdIndexRoute: typeof ConnectionIdProjectIdIndexRoute
  ConnectionIdProjectIdNewDraftIdRoute: typeof ConnectionIdProjectIdNewDraftIdRoute
  ConnectionIdProjectIdSessionSessionIdFilesRoute: typeof ConnectionIdProjectIdSessionSessionIdFilesRoute
  ConnectionIdProjectIdSessionSessionIdReviewRoute: typeof ConnectionIdProjectIdSessionSessionIdReviewRoute
  ConnectionIdProjectIdSessionSessionIdIndexRoute: typeof ConnectionIdProjectIdSessionSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/$connectionId/$projectId/': {
      id: '/$connectionId/$projectId/'
      path: '/$connectionId/$projectId'
      fullPath: '/$connectionId/$projectId/'
      preLoaderRoute: typeof ConnectionIdProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$connectionId/$section': {
      id: '/settings/$connectionId/$section'
      path: '/$connectionId/$section'
      fullPath: '/settings/$connectionId/$section'
      preLoaderRoute: typeof SettingsConnectionIdSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/$connectionId/$projectId/new/$draftId': {
      id: '/$connectionId/$projectId/new/$draftId'
      path: '/$connectionId/$projectId/new/$draftId'
      fullPath: '/$connectionId/$projectId/new/$draftId'
      preLoaderRoute: typeof ConnectionIdProjectIdNewDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/$projectId/session/$sessionId/': {
      id: '/$connectionId/$projectId/session/$sessionId/'
      path: '/$connectionId/$projectId/session/$sessionId'
      fullPath: '/$connectionId/$projectId/session/$sessionId/'
      preLoaderRoute: typeof ConnectionIdProjectIdSessionSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/$projectId/session/$sessionId/files': {
      id: '/$connectionId/$projectId/session/$sessionId/files'
      path: '/$connectionId/$projectId/session/$sessionId/files'
      fullPath: '/$connectionId/$projectId/session/$sessionId/files'
      preLoaderRoute: typeof ConnectionIdProjectIdSessionSessionIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/$projectId/session/$sessionId/review': {
      id: '/$connectionId/$projectId/session/$sessionId/review'
      path: '/$connectionId/$projectId/session/$sessionId/review'
      fullPath: '/$connectionId/$projectId/session/$sessionId/review'
      preLoaderRoute: typeof ConnectionIdProjectIdSessionSessionIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsConnectionIdSectionRoute: typeof SettingsConnectionIdSectionRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsConnectionIdSectionRoute: SettingsConnectionIdSectionRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ConnectionIdProjectIdIndexRoute: ConnectionIdProjectIdIndexRoute,
  ConnectionIdProjectIdNewDraftIdRoute: ConnectionIdProjectIdNewDraftIdRoute,
  ConnectionIdProjectIdSessionSessionIdFilesRoute:
    ConnectionIdProjectIdSessionSessionIdFilesRoute,
  ConnectionIdProjectIdSessionSessionIdReviewRoute:
    ConnectionIdProjectIdSessionSessionIdReviewRoute,
  ConnectionIdProjectIdSessionSessionIdIndexRoute:
    ConnectionIdProjectIdSessionSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
