/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionIdIndexRouteImport } from './routes/$connectionId.index'
import { Route as ConnectionIdSettingsRouteImport } from './routes/$connectionId.settings'
import { Route as ConnectionIdProjectIdIndexRouteImport } from './routes/$connectionId.$projectId.index'
import { Route as ConnectionIdSettingsIndexRouteImport } from './routes/$connectionId.settings.index'
import { Route as ConnectionIdSettingsSectionRouteImport } from './routes/$connectionId.settings.$section'
import { Route as ConnectionIdProjectIdNewDraftIdRouteImport } from './routes/$connectionId.$projectId.new.$draftId'
import { Route as ConnectionIdProjectIdSessionSessionIdIndexRouteImport } from './routes/$connectionId.$projectId.session.$sessionId.index'
import { Route as ConnectionIdProjectIdSessionSessionIdFilesRouteImport } from './routes/$connectionId.$projectId.session.$sessionId.files'
import { Route as ConnectionIdProjectIdSessionSessionIdReviewRouteImport } from './routes/$connectionId.$projectId.session.$sessionId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionIdIndexRoute = ConnectionIdIndexRouteImport.update({
  id: '/$connectionId/',
  path: '/$connectionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionIdSettingsRoute = ConnectionIdSettingsRouteImport.update({
  id: '/$connectionId/settings',
  path: '/$connectionId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionIdProjectIdIndexRoute =
  ConnectionIdProjectIdIndexRouteImport.update({
    id: '/$connectionId/$projectId/',
    path: '/$connectionId/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectionIdSettingsIndexRoute =
  ConnectionIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectionIdSettingsRoute,
  } as any)
const ConnectionIdSettingsSectionRoute =
  ConnectionIdSettingsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => ConnectionIdSettingsRoute,
  } as any)
const ConnectionIdProjectIdNewDraftIdRoute =
  ConnectionIdProjectIdNewDraftIdRouteImport.update({
    id: '/$connectionId/$projectId/new/$draftId',
    path: '/$connectionId/$projectId/new/$draftId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectionIdProjectIdSessionSessionIdIndexRoute =
  ConnectionIdProjectIdSessionSessionIdIndexRouteImport.update({
    id: '/$connectionId/$projectId/session/$sessionId/',
    path: '/$connectionId/$projectId/session/$sessionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectionIdProjectIdSessionSessionIdFilesRoute =
  ConnectionIdProjectIdSessionSessionIdFilesRouteImport.update({
    id: '/$connectionId/$projectId/session/$sessionId/files',
    path: '/$connectionId/$projectId/session/$sessionId/files',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectionIdProjectIdSessionSessionIdReviewRoute =
  ConnectionIdProjectIdSessionSessionIdReviewRouteImport.update({
    id: '/$connectionId/$projectId/session/$sessionId/review',
    path: '/$connectionId/$projectId/session/$sessionId/review',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$connectionId/settings': typeof ConnectionIdSettingsRouteWithChildren
  '/$connectionId/': typeof ConnectionIdIndexRoute
  '/$connectionId/settings/$section': typeof ConnectionIdSettingsSectionRoute
  '/$connectionId/$projectId/': typeof ConnectionIdProjectIdIndexRoute
  '/$connectionId/settings/': typeof ConnectionIdSettingsIndexRoute
  '/$connectionId/$projectId/new/$draftId': typeof ConnectionIdProjectIdNewDraftIdRoute
  '/$connectionId/$projectId/session/$sessionId/files': typeof ConnectionIdProjectIdSessionSessionIdFilesRoute
  '/$connectionId/$projectId/session/$sessionId/review': typeof ConnectionIdProjectIdSessionSessionIdReviewRoute
  '/$connectionId/$projectId/session/$sessionId/': typeof ConnectionIdProjectIdSessionSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$connectionId': typeof ConnectionIdIndexRoute
  '/$connectionId/settings/$section': typeof ConnectionIdSettingsSectionRoute
  '/$connectionId/$projectId': typeof ConnectionIdProjectIdIndexRoute
  '/$connectionId/settings': typeof ConnectionIdSettingsIndexRoute
  '/$connectionId/$projectId/new/$draftId': typeof ConnectionIdProjectIdNewDraftIdRoute
  '/$connectionId/$projectId/session/$sessionId/files': typeof ConnectionIdProjectIdSessionSessionIdFilesRoute
  '/$connectionId/$projectId/session/$sessionId/review': typeof ConnectionIdProjectIdSessionSessionIdReviewRoute
  '/$connectionId/$projectId/session/$sessionId': typeof ConnectionIdProjectIdSessionSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$connectionId/settings': typeof ConnectionIdSettingsRouteWithChildren
  '/$connectionId/': typeof ConnectionIdIndexRoute
  '/$connectionId/settings/$section': typeof ConnectionIdSettingsSectionRoute
  '/$connectionId/$projectId/': typeof ConnectionIdProjectIdIndexRoute
  '/$connectionId/settings/': typeof ConnectionIdSettingsIndexRoute
  '/$connectionId/$projectId/new/$draftId': typeof ConnectionIdProjectIdNewDraftIdRoute
  '/$connectionId/$projectId/session/$sessionId/files': typeof ConnectionIdProjectIdSessionSessionIdFilesRoute
  '/$connectionId/$projectId/session/$sessionId/review': typeof ConnectionIdProjectIdSessionSessionIdReviewRoute
  '/$connectionId/$projectId/session/$sessionId/': typeof ConnectionIdProjectIdSessionSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$connectionId/settings'
    | '/$connectionId/'
    | '/$connectionId/settings/$section'
    | '/$connectionId/$projectId/'
    | '/$connectionId/settings/'
    | '/$connectionId/$projectId/new/$draftId'
    | '/$connectionId/$projectId/session/$sessionId/files'
    | '/$connectionId/$projectId/session/$sessionId/review'
    | '/$connectionId/$projectId/session/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$connectionId'
    | '/$connectionId/settings/$section'
    | '/$connectionId/$projectId'
    | '/$connectionId/settings'
    | '/$connectionId/$projectId/new/$draftId'
    | '/$connectionId/$projectId/session/$sessionId/files'
    | '/$connectionId/$projectId/session/$sessionId/review'
    | '/$connectionId/$projectId/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/$connectionId/settings'
    | '/$connectionId/'
    | '/$connectionId/settings/$section'
    | '/$connectionId/$projectId/'
    | '/$connectionId/settings/'
    | '/$connectionId/$projectId/new/$draftId'
    | '/$connectionId/$projectId/session/$sessionId/files'
    | '/$connectionId/$projectId/session/$sessionId/review'
    | '/$connectionId/$projectId/session/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionIdSettingsRoute: typeof ConnectionIdSettingsRouteWithChildren
  ConnectionIdIndexRoute: typeof ConnectionIdIndexRoute
  ConnectionIdProjectIdIndexRoute: typeof ConnectionIdProjectIdIndexRoute
  ConnectionIdProjectIdNewDraftIdRoute: typeof ConnectionIdProjectIdNewDraftIdRoute
  ConnectionIdProjectIdSessionSessionIdFilesRoute: typeof ConnectionIdProjectIdSessionSessionIdFilesRoute
  ConnectionIdProjectIdSessionSessionIdReviewRoute: typeof ConnectionIdProjectIdSessionSessionIdReviewRoute
  ConnectionIdProjectIdSessionSessionIdIndexRoute: typeof ConnectionIdProjectIdSessionSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/': {
      id: '/$connectionId/'
      path: '/$connectionId'
      fullPath: '/$connectionId/'
      preLoaderRoute: typeof ConnectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/settings': {
      id: '/$connectionId/settings'
      path: '/$connectionId/settings'
      fullPath: '/$connectionId/settings'
      preLoaderRoute: typeof ConnectionIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/$projectId/': {
      id: '/$connectionId/$projectId/'
      path: '/$connectionId/$projectId'
      fullPath: '/$connectionId/$projectId/'
      preLoaderRoute: typeof ConnectionIdProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/settings/': {
      id: '/$connectionId/settings/'
      path: '/'
      fullPath: '/$connectionId/settings/'
      preLoaderRoute: typeof ConnectionIdSettingsIndexRouteImport
      parentRoute: typeof ConnectionIdSettingsRoute
    }
    '/$connectionId/settings/$section': {
      id: '/$connectionId/settings/$section'
      path: '/$section'
      fullPath: '/$connectionId/settings/$section'
      preLoaderRoute: typeof ConnectionIdSettingsSectionRouteImport
      parentRoute: typeof ConnectionIdSettingsRoute
    }
    '/$connectionId/$projectId/new/$draftId': {
      id: '/$connectionId/$projectId/new/$draftId'
      path: '/$connectionId/$projectId/new/$draftId'
      fullPath: '/$connectionId/$projectId/new/$draftId'
      preLoaderRoute: typeof ConnectionIdProjectIdNewDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/$projectId/session/$sessionId/': {
      id: '/$connectionId/$projectId/session/$sessionId/'
      path: '/$connectionId/$projectId/session/$sessionId'
      fullPath: '/$connectionId/$projectId/session/$sessionId/'
      preLoaderRoute: typeof ConnectionIdProjectIdSessionSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/$projectId/session/$sessionId/files': {
      id: '/$connectionId/$projectId/session/$sessionId/files'
      path: '/$connectionId/$projectId/session/$sessionId/files'
      fullPath: '/$connectionId/$projectId/session/$sessionId/files'
      preLoaderRoute: typeof ConnectionIdProjectIdSessionSessionIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$connectionId/$projectId/session/$sessionId/review': {
      id: '/$connectionId/$projectId/session/$sessionId/review'
      path: '/$connectionId/$projectId/session/$sessionId/review'
      fullPath: '/$connectionId/$projectId/session/$sessionId/review'
      preLoaderRoute: typeof ConnectionIdProjectIdSessionSessionIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConnectionIdSettingsRouteChildren {
  ConnectionIdSettingsSectionRoute: typeof ConnectionIdSettingsSectionRoute
  ConnectionIdSettingsIndexRoute: typeof ConnectionIdSettingsIndexRoute
}

const ConnectionIdSettingsRouteChildren: ConnectionIdSettingsRouteChildren = {
  ConnectionIdSettingsSectionRoute: ConnectionIdSettingsSectionRoute,
  ConnectionIdSettingsIndexRoute: ConnectionIdSettingsIndexRoute,
}

const ConnectionIdSettingsRouteWithChildren =
  ConnectionIdSettingsRoute._addFileChildren(ConnectionIdSettingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionIdSettingsRoute: ConnectionIdSettingsRouteWithChildren,
  ConnectionIdIndexRoute: ConnectionIdIndexRoute,
  ConnectionIdProjectIdIndexRoute: ConnectionIdProjectIdIndexRoute,
  ConnectionIdProjectIdNewDraftIdRoute: ConnectionIdProjectIdNewDraftIdRoute,
  ConnectionIdProjectIdSessionSessionIdFilesRoute:
    ConnectionIdProjectIdSessionSessionIdFilesRoute,
  ConnectionIdProjectIdSessionSessionIdReviewRoute:
    ConnectionIdProjectIdSessionSessionIdReviewRoute,
  ConnectionIdProjectIdSessionSessionIdIndexRoute:
    ConnectionIdProjectIdSessionSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
