name: generate

on:
  push:
    branches:
      - develop

jobs:
  generate:
    if: github.actor != 'hena[bot]'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup git committer
        id: committer
        uses: ./.github/actions/setup-git-committer
        with:
          hena-app-id: ${{ vars.HENA_APP_ID }}
          hena-app-secret: ${{ secrets.HENA_APP_SECRET }}

      - name: Generate
        run: ./script/generate.ts

      - name: Commit and push
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git add -A
          git commit -m "chore: generate"
          git push origin HEAD:${{ github.ref_name }} --no-verify
