name: knip

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  knip:
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Find unused code
        run: bun run knip --no-progress --reporter github-actions
