name: release-github-action

on:
  push:
    branches:
      - develop
    paths:
      - "github/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup git committer
        uses: ./.github/actions/setup-git-committer
        with:
          hena-app-id: ${{ vars.HENA_APP_ID }}
          hena-app-secret: ${{ secrets.HENA_APP_SECRET }}

      - run: git fetch --force --tags

      - name: Release
        run: ./github/script/release
